=== DCuadraLara/my-code-vault-dcl/FP/LM/tema1/biblioteca/biblioteca.dtd
<!ELEMENT biblioteca(libro+, enciclopedia+)>
<!ELEMENT libro (titulo, autores+, año_publicación)>
<!ELEMENT enciclopedia (titulo, editorial, temática)>
<!ATTLIST libro 
id ID #REQUIRED
>
<!ATTLIST enciclopedia 
id ID #REQUIRED
>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autores (#PCDATA)>
<!ELEMENT año_publicación (#PCDATA)>
<!ELEMENT editorial (#PCDATA)>
<!ELEMENT temática (#PCDATA)>

=== DCuadraLara/my-code-vault-dcl/FP/LM/tema1/biblioteca/biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "/C/USERS/DAVIL/DESKTOP/biblioteca.dtd">
<!--
David Cuadra Lara

Biblioteca

Crea un documento XML bien formado para estructurar una biblioteca.
La biblioteca almacena libros y enciclopedias.
De cada libro guardaremos el titulo, uno o varios autores y el año de publicación.
De cada enciclopedia guardaremos: el título, la editorial y la temática (general, geográfica, medicina, historia)
Una vez creada la estructura inventa la información de dos libros y dos enciclopedias.

-->
<biblioteca>
	<libro>
		<titulo id="B001">Unknown, El primero</titulo>
		<autores>Luis desaparecido</autores>
		<año_publicación>1960</año_publicación>
	</libro>
	<libro>
		<titulo id="A023">Unknown, El segundo</titulo>
		<autores>Luis aparecido</autores>
		<autores>Luisillo</autores>
		<año_publicación>1920</año_publicación>
	</libro>
	<enciclopedia>
		<titulo id="V093">La verdad del mundo</titulo>
		<editorial>losabetodo</editorial>
		<temática>historia</temática>
	</enciclopedia>
	<enciclopedia>
		<titulo id="K394">La mentira el mundo</titulo>
		<editorial>nosabenada</editorial>
		<temática>historia</temática>
	</enciclopedia>
</biblioteca>
