=== DCuadraLara/my-code-vault-dcl/FP/LM/tema1/EjercicioReggio/reggio.dtd
<!ELEMENT Reggio(establecimiento+)>
<!ELEMENT establecimiento(pedido+, tienda, almacen)>
<!ELEMENT pedido(datos, nombre_empleado, fecha, articulos+)>
<!ELEMENT nombre_empleado (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT tienda(albaran, pago)>
<!ELEMENT almacen EMPTY>
<!ATTLIST pedido 
cod_pedido ID #REQUIRED 
tipo(URGENTE | NORMAL) #REQUIRED
>
<!ATTLIST tienda 
pedido_ref IDREF #REQUIRED
>
<!ATTLIST almacen 
id_almacen ID #REQUIRED 
pedido_ref IDREF #REQUIRED 
estado(RECIBIDO | PENDIENTE) #REQUIRED
>
<!ELEMENT datos(nombre, direccion_envio, direccion_almacen?)>
<!ELEMENT direccion_envio(Via, numero, localidad, provincia, cp)>
<!ELEMENT direccion_almacen(Via, numero, localidad, provincia, cp)>
<!ELEMENT articulos(cantidad, precio, observaciones?)>
<!ATTLIST articulos 
cod_articulo ID #REQUIRED
>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT Via (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT cp (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ATTLIST precio 
CDATA #FIXED "EUR"
>
<!ELEMENT observaciones (#PCDATA)>
<!ELEMENT albaran (fecha, observaciones?)>
<!ATTLIST albaran estado(RECIBIDO | PENDIENTE) #REQUIRED>
<!ELEMENT pago EMPTY>
<!ATTLIST pago estado (PAGADO | PENDIENTE) #REQUIRED fecha CDATA #REQUIRED>

=== DCuadraLara/my-code-vault-dcl/FP/LM/tema1/EjercicioReggio/reggio.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Reggio SYSTEM "Reggio.dtd">

<Reggio>
	<establecimiento>
		<pedido cod_pedido="A180001-22" tipo="URGENTE">
				<datos>
					<nombre>Lucas</nombre>
					<direccion_envio>
						<Via>Calle molina</Via>
						<numero>8</numero>
						<localidad>Rincón de la victoria</localidad>
						<provincia>Málaga</provincia>
						<cp>29730</cp>
					</direccion_envio>
					<direccion_almacen>
						<Via>Calle muelles</Via>
						<numero>2</numero>
						<localidad>Rincón de la victoria</localidad>
						<provincia>Málaga</provincia>
						<cp>29730</cp>
					</direccion_almacen>
				</datos>
				<nombre_empleado>David</nombre_empleado>
				<fecha>2022-04-22</fecha>
				<articulos cod_articulo="ABC123">
					<cantidad>8</cantidad>
					<precio moneda="EUR">8.80</precio>
					<observaciones>Cuidado es frágil</observaciones>
				</articulos>
		</pedido>
		<tienda pedido_ref="A180001-22">
			<albaran estado="RECIBIDO">
				<fecha>2022-12-12</fecha>
				<observaciones>Falta un producto</observaciones>
			</albaran>
			<pago estado="PAGADO" fecha="2022-12-15"/>
		</tienda>
		<almacen id_almacen="B123" pedido_ref="A180001-22" estado="RECIBIDO"/>
	</establecimiento>
</Reggio>
